version: '3.4'

services:
  postgres:
    container_name: db
    image: postgres:16
    environment:
      POSTGRES_DB: "storage"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
