# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  ssu.dm.webassembly.server:
    build:
      context: "C:\\Users\\droll\\Desktop\\DiplomFiles\\SSU.DepManagement"
      dockerfile: "SSU.DM.WebAssembly/Server/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-x64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/SSU.DM.WebAssembly.Server.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "C:\\Users\\droll\\.nuget\\packages"
      NUGET_FALLBACK_PACKAGES: "C:\\Users\\droll\\.nuget\\packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "ssudmwebassemblyserver:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "C:\\Users\\droll\\.nuget\\packages:/root/.nuget/fallbackpackages"
    - "C:\\Users\\droll\\Desktop\\DiplomFiles\\SSU.DepManagement\\SSU.DM.WebAssembly\\\
      Server:/app:rw"
    - "C:\\Users\\droll\\Desktop\\DiplomFiles\\SSU.DepManagement:/src:rw"
    - "C:\\Users\\droll\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2023.2.1\\\
      Linux64:/riderDebugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2023.2.1/bin:/riderLogsConf"
    - "C:\\Users\\droll\\AppData\\Local\\JetBrains\\Rider2023.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2023_10_07_17_15_23:/riderLogs:rw"
    working_dir: "/app"
